spring:
  application:
    name: techefx-spring-cloud-config-server
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chndnc3/environment-variable-repo.git
  
server:
  port: 8888